name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurer les dépendances
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Exécuter les tests
        run: dotnet test --no-build --configuration Release --verbosity normal